// ----------------------------------------------------------------------------
// <auto-generated>
// This is autogenerated code by Embeddinator-4000.
// Do not edit this file or all your changes will be lost after re-generation.
// </auto-generated>
// ----------------------------------------------------------------------------
#include "mscorlib.h"
#include "glib.h"
#include "mono_embeddinator.h"
#include "c-support.h"

mono_embeddinator_context_t __mono_context;
MonoImage* __mscorlib_dll_image;

static MonoClass* class_System_IEquatable_1 = 0;
static MonoClass* class_System_IComparable_1 = 0;
static MonoClass* class_System_IComparable = 0;
static MonoClass* class_System_Collections_IStructuralEquatable = 0;
static MonoClass* class_System_Collections_IStructuralComparable = 0;

static void __initialize_mono()
{
    if (__mono_context.domain)
        return;
    mono_embeddinator_init(&__mono_context, "mono_embeddinator_binding");
}

static void __lookup_assembly_mscorlib_dll()
{
    if (__mscorlib_dll_image)
        return;
    __mscorlib_dll_image = mono_embeddinator_load_assembly(&__mono_context, "mscorlib.dll");
}

static void __lookup_class_System_Collections_IStructuralEquatable()
{
    if (class_System_Collections_IStructuralEquatable == 0)
    {
        __initialize_mono();
        __lookup_assembly_mscorlib_dll();
        class_System_Collections_IStructuralEquatable = mono_class_from_name(__mscorlib_dll_image, "System.Collections", "IStructuralEquatable");
    }
}

static void __lookup_class_System_Collections_IStructuralComparable()
{
    if (class_System_Collections_IStructuralComparable == 0)
    {
        __initialize_mono();
        __lookup_assembly_mscorlib_dll();
        class_System_Collections_IStructuralComparable = mono_class_from_name(__mscorlib_dll_image, "System.Collections", "IStructuralComparable");
    }
}

static void __lookup_class_System_IComparable()
{
    if (class_System_IComparable == 0)
    {
        __initialize_mono();
        __lookup_assembly_mscorlib_dll();
        class_System_IComparable = mono_class_from_name(__mscorlib_dll_image, "System", "IComparable");
    }
}
