// ----------------------------------------------------------------------------
// <auto-generated>
// This is autogenerated code by Embeddinator-4000.
// Do not edit this file or all your changes will be lost after re-generation.
// </auto-generated>
// ----------------------------------------------------------------------------
#pragma once

#include "glib.h"
#include "mono_embeddinator.h"
#include "c-support.h"

MONO_EMBEDDINATOR_BEGIN_DECLS

typedef MonoEmbedObject System_IEquatable_1;
typedef MonoEmbedObject System_IComparable_1;
typedef MonoEmbedObject System_IComparable;
typedef MonoEmbedObject System_Collections_IStructuralEquatable;
typedef MonoEmbedObject System_Collections_IStructuralComparable;

MONO_EMBEDDINATOR_END_DECLS
