// ----------------------------------------------------------------------------
// <auto-generated>
// This is autogenerated code by Embeddinator-4000.
// Do not edit this file or all your changes will be lost after re-generation.
// </auto-generated>
// ----------------------------------------------------------------------------
#pragma once

#include "glib.h"
#include "mono_embeddinator.h"
#include "c-support.h"

MONO_EMBEDDINATOR_BEGIN_DECLS

typedef enum System_Text_RegularExpressions_RegexOptions
{
    System_Text_RegularExpressions_RegexOptions_None = 0,
    System_Text_RegularExpressions_RegexOptions_IgnoreCase = 1,
    System_Text_RegularExpressions_RegexOptions_Multiline = 2,
    System_Text_RegularExpressions_RegexOptions_ExplicitCapture = 4,
    System_Text_RegularExpressions_RegexOptions_Compiled = 8,
    System_Text_RegularExpressions_RegexOptions_Singleline = 16,
    System_Text_RegularExpressions_RegexOptions_IgnorePatternWhitespace = 32,
    System_Text_RegularExpressions_RegexOptions_RightToLeft = 64,
    System_Text_RegularExpressions_RegexOptions_ECMAScript = 256,
    System_Text_RegularExpressions_RegexOptions_CultureInvariant = 512
} System_Text_RegularExpressions_RegexOptions;

MONO_EMBEDDINATOR_END_DECLS
